/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jyyu' at '7/24/15 10:39 AM' with Gradle 2.5
 *
 * @author jyyu, @date 7/24/15 10:39 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
